basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: Nugs Collection API Support
  description: Comprehensive REST API for managing music collections, downloads, monitoring,
    and analytics with enterprise-grade features including background job processing,
    webhook notifications, and detailed analytics.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://example.com/terms
  title: Nugs Collection API
  version: 1.0.0
paths: {}
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
